#!/bin/bash
# MJ CARGO - TEST CUSTOMER NAME LINKS

echo "🔗 TESTING CUSTOMER NAME LINKS"
echo "=============================="
echo ""
echo "✅ CHANGES APPLIED:"
echo "  • Customer names are now clickable links"
echo "  • Names appear in orange color (#ee6832)"  
echo "  • Hover effect: underline + darker orange"
echo "  • Links go to same destination as View button"
echo ""
echo "📍 FILE MODIFIED:"
echo "  C:\Users\kence\salesdash-ts\app\[lang]\(dashboard)\(apps)\crm\customers\page.tsx"
echo ""
echo "🎨 STYLING APPLIED:"
echo "  • text-orange-600 (default color)"
echo "  • hover:text-orange-700 (hover color)"
echo "  • hover:underline (underline on hover)"
echo "  • cursor-pointer (pointer cursor)"
echo ""
echo "🔄 TO TEST:"
echo "  1. Restart dev server: pnpm dev"
echo "  2. Go to: http://localhost:3000/en/crm/customers"
echo "  3. Click on any customer name"
echo "  4. Should navigate to: /en/crm/customers/{id}"
echo ""
echo "✅ BOTH NAME AND VIEW BUTTON NOW WORK!"
echo ""
echo "¡Listo hermano! Customer names are clickable! 🚀"
