import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// Full MJ Cargo trailer lineup
const SAMPLE_TRAILERS = [
  // ============ SINGLE AXLE TRAILERS ============
  {
    id: "1",
    vin: "1MJSA5X10P1000001",
    stockNumber: "MJ-2025-001",
    manufacturer: "MJ Cargo",
    model: "5X10SA White .030 R",
    year: 2025,
    category: "Utility",
    length: 10,
    width: 5,
    msrp: 2299,
    salePrice: 1999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "Aluminum Skin", "White"],
  },
  {
    id: "2",
    vin: "1MJSA6X12P1000002",
    stockNumber: "MJ-2025-002",
    manufacturer: "MJ Cargo",
    model: "6X12SA Black .080 R VN",
    year: 2025,
    category: "Utility",
    length: 12,
    width: 6,
    msrp: 3499,
    salePrice: 3199,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Black Polycore", "Premium"],
  },
  {
    id: "3",
    vin: "1MJSA7X14P1000003",
    stockNumber: "MJ-2025-003",
    manufacturer: "MJ Cargo",
    model: "7X14SA White .030 R",
    year: 2025,
    category: "Utility",
    length: 14,
    width: 7,
    msrp: 3799,
    salePrice: 3399,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(), // 1 day old
    daysOld: 1,
    features: ["Ramp Door", "Aluminum Skin", "White"],
  },
  {
    id: "4",
    vin: "1MJSA7X16P1000004",
    stockNumber: "MJ-2025-004",
    manufacturer: "MJ Cargo",
    model: "7X16SA Silver Frost .030 R VN",
    year: 2025,
    category: "Utility",
    length: 16,
    width: 7,
    msrp: 4199,
    salePrice: 3799,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Silver Frost", "Aluminum Skin"],
  },

  // ============ TANDEM AXLE TRAILERS ============
  {
    id: "5",
    vin: "1MJTA7X14P1000005",
    stockNumber: "MJ-2025-005",
    manufacturer: "MJ Cargo",
    model: "7X14TA2 White .030 R DD",
    year: 2025,
    category: "Utility",
    length: 14,
    width: 7,
    msrp: 4599,
    salePrice: 4199,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(), // 2 days old
    daysOld: 2,
    features: ["Ramp Door", "Double Doors", "Tandem Axle", "3500lb Axles", "White"],
  },
  {
    id: "6",
    vin: "1MJTA7X16P1000006",
    stockNumber: "MJ-2025-006",
    manufacturer: "MJ Cargo",
    model: "7X16TA2 Black .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 7,
    msrp: 6299,
    salePrice: 5799,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Black Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "7",
    vin: "1MJTA7X18P1000007",
    stockNumber: "MJ-2025-007",
    manufacturer: "MJ Cargo",
    model: "7X18TA2 Charcoal Gray .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 18,
    width: 7,
    msrp: 6799,
    salePrice: 6299,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Charcoal Gray Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "8",
    vin: "1MJTA7X20P1000008",
    stockNumber: "MJ-2025-008",
    manufacturer: "MJ Cargo",
    model: "7X20TA2 White .030 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 20,
    width: 7,
    msrp: 6999,
    salePrice: 6499,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Ramp Door", "V-Nose", "White", "7' Interior", "Tandem Axle", "Aluminum Skin"],
  },

  // ============ 8.5' WIDE TRAILERS ============
  {
    id: "9",
    vin: "1MJTA8X16P1000009",
    stockNumber: "MJ-2025-009",
    manufacturer: "MJ Cargo",
    model: "8.5X16TA2 Black .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 8.5,
    msrp: 7499,
    salePrice: 6999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Black Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "10",
    vin: "1MJTA8X18P1000010",
    stockNumber: "MJ-2025-010",
    manufacturer: "MJ Cargo",
    model: "8.5X18TA2 Silver Frost .030 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 18,
    width: 8.5,
    msrp: 7799,
    salePrice: 7299,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Silver Frost", "7' Interior", "Tandem Axle", "Aluminum Skin"],
  },
  {
    id: "11",
    vin: "1MJTA8X20P1000011",
    stockNumber: "MJ-2025-011",
    manufacturer: "MJ Cargo",
    model: "8.5X20TA2 White .030 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 20,
    width: 8.5,
    msrp: 8299,
    salePrice: 7799,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Ramp Door", "V-Nose", "White", "7' Interior", "Tandem Axle", "Aluminum Skin"],
  },
  {
    id: "12",
    vin: "1MJTA8X24P1000012",
    stockNumber: "MJ-2025-012",
    manufacturer: "MJ Cargo",
    model: "8.5X24TA3 Black .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 24,
    width: 8.5,
    msrp: 10999,
    salePrice: 9999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Black Polycore", "7' Interior", "Heavy Duty", "5200lb Axles", "Premium"],
  },

  // ============ PREMIUM/SPECIALTY TRAILERS ============
  {
    id: "13",
    vin: "1MJTA7X16P1000013",
    stockNumber: "MJ-2025-013",
    manufacturer: "MJ Cargo",
    model: "7X16TA2 Emerald Green .080 R VN 7' SRW",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 7,
    msrp: 7299,
    salePrice: 6799,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Emerald Green Polycore", "7' Interior", "Screwless", "Tandem Axle", "Premium"],
  },
  {
    id: "14",
    vin: "1MJTA7X16P1000014",
    stockNumber: "MJ-2025-014",
    manufacturer: "MJ Cargo",
    model: "7X16TA2 Orange/Black .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 7,
    msrp: 7499,
    salePrice: 6999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Two-Tone Orange/Black", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "15",
    vin: "1MJTA8X20P1000015",
    stockNumber: "MJ-2025-015",
    manufacturer: "MJ Cargo",
    model: "8.5X20TA2 Black/White .080 R VN 7' SRW",
    year: 2025,
    category: "Enclosed",
    length: 20,
    width: 8.5,
    msrp: 9999,
    salePrice: 9299,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Two-Tone Black/White", "7' Interior", "Screwless", "Tandem Axle", "Premium"],
  },

  // ============ CONCESSION TRAILERS ============
  {
    id: "16",
    vin: "1MJTA8X16P1000016",
    stockNumber: "MJ-2025-016",
    manufacturer: "MJ Cargo",
    model: "8.5X16TA2 White .080 Concession 7'",
    year: 2025,
    category: "Concession",
    length: 16,
    width: 8.5,
    msrp: 14999,
    salePrice: 13999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Concession Window", "AC Unit", "Electrical Package", "Vinyl Walls", "7' Interior", "Polycore", "Tandem Axle"],
  },
  {
    id: "17",
    vin: "1MJTA8X20P1000017",
    stockNumber: "MJ-2025-017",
    manufacturer: "MJ Cargo",
    model: "8.5X20TA3 White .080 Concession 7'",
    year: 2025,
    category: "Concession",
    length: 20,
    width: 8.5,
    msrp: 18999,
    salePrice: 17499,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    daysOld: 3,
    features: ["Concession Window", "AC w/ Heat Strip", "50 AMP Electrical", "Vinyl Walls", "7' Interior", "Heavy Duty", "5200lb Axles"],
  },

  // ============ DUMP TRAILERS ============
  {
    id: "18",
    vin: "1MJDT7X12P1000018",
    stockNumber: "MJ-2025-018",
    manufacturer: "MJ Cargo",
    model: "7X12DT Single Axle Dump",
    year: 2025,
    category: "Dump",
    length: 12,
    width: 7,
    msrp: 6499,
    salePrice: 5999,
    status: "available",
    location: "Back Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Hydraulic Dump", "Single Axle", "7000 GVWR"],
  },
  {
    id: "19",
    vin: "1MJDT7X14P1000019",
    stockNumber: "MJ-2025-019",
    manufacturer: "MJ Cargo",
    model: "7X14DT Tandem Axle Dump",
    year: 2025,
    category: "Dump",
    length: 14,
    width: 7,
    msrp: 8999,
    salePrice: 8299,
    status: "available",
    location: "Back Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Hydraulic Dump", "Tandem Axle", "14000 GVWR", "Heavy Duty"],
  },

  // ============ CAR HAULERS ============
  {
    id: "20",
    vin: "1MJCH8X18P1000020",
    stockNumber: "MJ-2025-020",
    manufacturer: "MJ Cargo",
    model: "8.5X18CH Car Hauler",
    year: 2025,
    category: "Car Hauler",
    length: 18,
    width: 8.5,
    msrp: 7999,
    salePrice: 7499,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Dove Tail", "D-Rings", "Tandem Axle", "7000 GVWR"],
  },
  {
    id: "21",
    vin: "1MJCH8X20P1000021",
    stockNumber: "MJ-2025-021",
    manufacturer: "MJ Cargo",
    model: "8.5X20CH Car Hauler Enclosed",
    year: 2025,
    category: "Car Hauler",
    length: 20,
    width: 8.5,
    msrp: 9999,
    salePrice: 9299,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Enclosed", "Ramp Door", "D-Rings", "Tandem Axle", "7' Interior", "Aluminum Wheels"],
  },

  // ============ GOOSENECK TRAILERS ============
  {
    id: "22",
    vin: "1MJGN8X20P1000022",
    stockNumber: "MJ-2025-022",
    manufacturer: "MJ Cargo",
    model: "8.5X20GN Gooseneck Flatbed",
    year: 2025,
    category: "Gooseneck",
    length: 20,
    width: 8.5,
    msrp: 10999,
    salePrice: 9999,
    status: "available",
    location: "Back Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Gooseneck", "Flatbed", "Tandem Axle", "14000 GVWR", "Heavy Duty"],
  },
  {
    id: "23",
    vin: "1MJGN8X24P1000023",
    stockNumber: "MJ-2025-023",
    manufacturer: "MJ Cargo",
    model: "8.5X24GN Gooseneck Enclosed",
    year: 2025,
    category: "Gooseneck",
    length: 24,
    width: 8.5,
    msrp: 14999,
    salePrice: 13999,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Gooseneck", "Enclosed", "Ramp Door", "7' Interior", "Heavy Duty", "5200lb Axles"],
  },

  // ============ MOTORCYCLE TRAILERS ============
  {
    id: "24",
    vin: "1MJSA5X8P1000024",
    stockNumber: "MJ-2025-024",
    manufacturer: "MJ Cargo",
    model: "5X8SA Black .030 Motorcycle Trailer",
    year: 2025,
    category: "Motorcycle",
    length: 8,
    width: 5,
    msrp: 2199,
    salePrice: 1899,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Motorcycle Chock", "D-Rings", "Aluminum Skin", "Black", "Single Axle"],
  },

  // ============ RESERVED/SOLD TRAILERS ============
  {
    id: "25",
    vin: "1MJTA7X16P1000025",
    stockNumber: "MJ-2025-025",
    manufacturer: "MJ Cargo",
    model: "7X16TA2 Black .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 7,
    msrp: 6299,
    salePrice: 5799,
    status: "reserved",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    daysOld: 3,
    features: ["Ramp Door", "V-Nose", "Black Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "26",
    vin: "1MJTA8X20P1000026",
    stockNumber: "MJ-2025-026",
    manufacturer: "MJ Cargo",
    model: "8.5X20TA2 Charcoal Gray .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 20,
    width: 8.5,
    msrp: 8999,
    salePrice: 8299,
    status: "sold",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    daysOld: 5,
    features: ["Ramp Door", "V-Nose", "Charcoal Gray Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },

  // ============ ADDITIONAL VARIATIONS ============
  {
    id: "27",
    vin: "1MJTA7X12P1000027",
    stockNumber: "MJ-2025-027",
    manufacturer: "MJ Cargo",
    model: "7X12TA2 White .030 R",
    year: 2025,
    category: "Utility",
    length: 12,
    width: 7,
    msrp: 4299,
    salePrice: 3899,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "Tandem Axle", "White", "Aluminum Skin", "3500lb Axles"],
  },
  {
    id: "28",
    vin: "1MJTA6X12P1000028",
    stockNumber: "MJ-2025-028",
    manufacturer: "MJ Cargo",
    model: "6X12TA2 Red .030 R VN",
    year: 2025,
    category: "Utility",
    length: 12,
    width: 6,
    msrp: 3999,
    salePrice: 3599,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date().toISOString(),
    daysOld: 0,
    features: ["Ramp Door", "V-Nose", "Red", "Aluminum Skin", "Tandem Axle"],
  },
  {
    id: "29",
    vin: "1MJTA8X16P1000029",
    stockNumber: "MJ-2025-029",
    manufacturer: "MJ Cargo",
    model: "8.5X16TA2 Indigo Blue .080 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 16,
    width: 8.5,
    msrp: 8299,
    salePrice: 7799,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    daysOld: 1,
    features: ["Ramp Door", "V-Nose", "Indigo Blue Polycore", "7' Interior", "Tandem Axle", "Premium"],
  },
  {
    id: "30",
    vin: "1MJTA8X22P1000030",
    stockNumber: "MJ-2025-030",
    manufacturer: "MJ Cargo",
    model: "8.5X22TA2 White .030 R VN 7'",
    year: 2025,
    category: "Enclosed",
    length: 22,
    width: 8.5,
    msrp: 8799,
    salePrice: 8199,
    status: "available",
    location: "Main Lot",
    images: ["/images/trailer-placeholder.jpg"],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    daysOld: 2,
    features: ["Ramp Door", "V-Nose", "White", "7' Interior", "Tandem Axle", "Aluminum Skin"],
  },
];

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const statusFilter = searchParams.get("status");
    const categoryFilter = searchParams.get("category");

    // Fetch real trailers from database
    const whereClause: any = {};

    if (statusFilter && statusFilter !== "all") {
      whereClause.status = statusFilter;
    }

    if (categoryFilter && categoryFilter !== "all") {
      whereClause.category = categoryFilter;
    }

    const trailers = await prisma.trailer.findMany({
      where: whereClause,
      orderBy: [
        { createdAt: 'desc' },
        { stockNumber: 'asc' }
      ]
    });

    // Calculate daysOld for each trailer
    const trailersWithAge = trailers.map(trailer => ({
      ...trailer,
      daysOld: Math.floor((Date.now() - new Date(trailer.createdAt).getTime()) / (1000 * 60 * 60 * 24))
    }));

    return NextResponse.json({ trailers: trailersWithAge });
  } catch (error) {
    console.error("Inventory fetch error:", error);
    return NextResponse.json(
      { error: "Failed to fetch inventory" },
      { status: 500 }
    );
  }
}

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();

    // Validate required fields
    const required = [
      "vin",
      "stockNumber",
      "manufacturer",
      "model",
      "year",
      "category",
      "length",
      "width",
      "msrp",
      "salePrice",
      "cost",
    ];

    for (const field of required) {
      if (!body[field]) {
        return NextResponse.json(
          { error: `Missing required field: ${field}` },
          { status: 400 }
        );
      }
    }

    // Create trailer
    const trailer = await prisma.trailer.create({
      data: {
        vin: body.vin,
        stockNumber: body.stockNumber,
        manufacturer: body.manufacturer,
        model: body.model,
        year: parseInt(body.year),
        category: body.category,
        length: parseFloat(body.length),
        width: parseFloat(body.width),
        height: body.height ? parseFloat(body.height) : null,
        gvwr: body.gvwr ? parseInt(body.gvwr) : null,
        capacity: body.capacity ? parseInt(body.capacity) : null,
        axles: body.axles ? parseInt(body.axles) : null,
        msrp: parseFloat(body.msrp),
        salePrice: parseFloat(body.salePrice),
        cost: parseFloat(body.cost),
        status: body.status || "available",
        location: body.location,
        images: body.images || [],
        description: body.description,
        features: body.features || [],
        createdBy: session.user.id,
      },
    });

    return NextResponse.json({ trailer }, { status: 201 });
  } catch (error: any) {
    console.error("Trailer creation error:", error);

    if (error.code === "P2002") {
      return NextResponse.json(
        { error: "VIN or Stock Number already exists" },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: "Failed to create trailer" },
      { status: 500 }
    );
  }
}
