#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "❌ Do not commit on main. Use feature/ or fix/ branch."
  exit 1
fi

pnpm lint || exit 1
